import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>DASATO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container py-28">
        <div className="grid grid-cols-2">
          <div className="flex flex-col items-center justify-center">
            <h1 className="text-h1 mb-5">
              Rozhovory s ľuďmi, ktorí dokázali, že sa to DÁ.
            </h1>
            <p className="text-3xl font-light leading-40">
              Inšpirácie a praktické návody, ako obyčajní ľudia dokážu
              neobyčajné veci.
            </p>
          </div>
        </div>
      </div>
    </>
  );
}
